pod 'AFNetworking'
pod 'Masonry', '~> 0.6.3'
pod 'SDWebImage', '~> 3.7.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh', '~> 3.0.2'
pod 'Realm', '~> 0.96.2'
pod 'YYModel', '~> 0.9.1'
pod 'LTNavigationBar’,’2.1.0'
pod 'WeiboSDK', '~> 3.1.3'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4.beta'
pod 'XLForm', '~> 3.1.1'
